FROM tensorflow/tensorflow:2.1.1-gpu

# 安装系统依赖
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    ffmpeg \
    vim \
    && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 安装Python依赖
RUN pip3 install --no-cache-dir ffmpeg-python \
    opencv-python \
    numpy \
    flask \
    gunicorn \
    pillow \
    tqdm \
    moviepy

# 暴露API端口
EXPOSE 5000

# 启动命令
CMD ["python3", "/app/server/api_server.py"]
