services:
  audio-separator:
    image: catchoco/as:gpu-v1.0
    container_name: audio-separator-gpu
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/app
      - ../../../data:/data
    ports:
      - "6000:6000"
    entrypoint: tail
    # command: [ "python", "/app/main.py" ]
    command: [ "-f", "/dev/null"]